import { createSlice } from '@reduxjs/toolkit';

const initialState = {
  data: [],       // Array for general data, maybe other resources
  loading: false, // Loading state
  error: null,    // Error state
  user: null      // User-specific data, could be profile data
};

// Create a slice for handling state changes
const authSlice = createSlice({
  name: 'auth', // Name for the slice
  initialState,
  reducers: {
    fetchDataRequest: (state) => {
      state.loading = true;
      state.error = null;  // Reset error on new request
    },
    fetchDataSuccess: (state, action) => {
      state.loading = false;
      state.data = action.payload; // Assuming this payload is an array
      state.user = action.payload; // If you are fetching user profile data
    },
    fetchDataFailure: (state, action) => {
      state.loading = false;
      state.error = action.payload; // Capture error
    },
  },
});

// Export the actions generated by createSlice
export const { fetchDataRequest, fetchDataSuccess, fetchDataFailure } = authSlice.actions;

export default authSlice.reducer;
