import { createSlice } from '@reduxjs/toolkit';

const initialState = {
  post: null,      // For single post data
  posts: [],       // For multiple posts
  loading: false,  // Loading state
  error: null,     // Error state
  like: null,      // For handling likes
};

// Create a slice for handling post-related state changes
const postSlice = createSlice({
  name: 'post', // Updated to 'post' for better clarity
  initialState,
  reducers: {
    fetchPostsRequest: (state) => {
      state.loading = true;
      state.error = null;  // Reset error on new request
    },
    fetchPostsSuccess: (state, action) => {
      state.loading = false;
      state.posts = action.payload; // Assuming the payload is an array of posts
    },
    fetchPostsFailure: (state, action) => {
      state.loading = false;
      state.error = action.payload; // Capture error
    },

    // For handling a single post fetch
    fetchPostRequest: (state) => {
      state.loading = true;
      state.error = null;  // Reset error on new request
    },
    fetchPostSuccess: (state, action) => {
      state.loading = false;
      state.post = action.payload; // Assuming the payload is a single post
    },
    fetchPostFailure: (state, action) => {
      state.loading = false;
      state.error = action.payload; // Capture error
    },

    // For handling post likes
    likePostRequest: (state) => {
      state.loading = true;
      state.error = null; // Reset error on new request
    },
    likePostSuccess: (state, action) => {
      state.loading = false;
      state.like = action.payload; // Assuming the payload contains like details
    },
    likePostFailure: (state, action) => {
      state.loading = false;
      state.error = action.payload; // Capture error
    },

    // // Optionally, add a reducer to reset the state
    // resetPostState: (state) => {
    //   state.post = null;
    //   state.posts = [];
    //   state.loading = false;
    //   state.error = null;
    //   state.like = null;
    // },
  },
});

// Export the actions generated by createSlice
export const { 
  fetchPostsRequest, fetchPostsSuccess, fetchPostsFailure,
  fetchPostRequest, fetchPostSuccess, fetchPostFailure,
  likePostRequest, likePostSuccess, likePostFailure
} = postSlice.actions;

export default postSlice.reducer;
